site_name: HAI
site_url: https://H-AI.github.io/H-AI.github.io/
nav:
  - Home: 'index.md'
  - Perception:
      - Logs: 'logs.md'
  - Introduction: 'about.md'
  - Mission Statement: 'mission.md'

# markdown_extensions:
#   - toc:
#     permalink: "#"

theme:
  name: material

